services:
  web:
    build:
      context: .
      dockerfile: ./inertia-web/dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - 8080:8080

  backend:
    build:
      context: .
      dockerfile: ./inertia-async-server/dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - 8001:8001
    command: inertia-async-server
    environment:
      DB_URL: sqlite:/app/db/boards.db?mode=ro

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx-proxy-manager-data:/data
      - ./letsencrypt:/etc/letsencrypt
