services:
  web:
    image: ${INERTIA_WEB_IMAGE}
    restart: unless-stopped

  backend:
    image: ${INERTIA_BACKEND_IMAGE}
    restart: unless-stopped
    environment:
      DB_URL: sqlite:/app/db/boards.db?mode=ro

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx-proxy-manager-data:/data
      - ./letsencrypt:/etc/letsencrypt
