[package]
name = "fdg-test"
version = "0.1.0"
edition = "2024"

[dependencies]
fdg = { git = "https://github.com/grantshandy/fdg" }
petgraph = { version = "0.7.1", default-features = false, features = [ "graphmap", "stable_graph", "matrix_graph", "serde-1" ] }
