[package]
name = "inertia-server"
version = "0.1.0"
edition = "2021"

[dependencies]
inertia-core = { path = "../inertia-core/" }
rouille = "3.6.2"
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"
