FROM rust:slim-bookworm AS rust-deps-build
RUN cargo install wasm-pack

COPY inertia-core /build/inertia-core
WORKDIR /build/inertia-core/
RUN cargo build --release
RUN ./script/build-web-types.sh


FROM node:20-bookworm-slim AS node-common
COPY --from=rust-deps-build /build/inertia-core/pkg /inertia-core/pkg
WORKDIR /app/
COPY inertia-web/package.json /app/
COPY inertia-web/package-lock.json /app/
RUN npm ci
COPY inertia-web/ /app/


FROM node-common AS dev


FROM node-common AS prod-build
RUN npm run build:prod


FROM nginx:latest AS prod
COPY --from=prod-build /app/public/ /app/dist/ /usr/share/nginx/html/
COPY inertia-web/nginx.prod.conf /etc/nginx/conf.d/default.conf
