[package]
name = "solver-profile"
version = "0.1.0"
edition = "2021"

[dependencies]
inertia-core = { path = "../inertia-core/" }
base64 = "0.21.5"
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
