[package]
name = "solver-profile"
version = "0.1.0"
edition = "2021"

[dependencies]
inertia-core = { path = "../inertia-core/" }
base64 = "0.22.1"
clap = { version = "4.5.41", features = ["derive"] }
colored = "3.0.0"
